type ReportApplication = {
  _id: unknown;
  fullName: string;
  phone: string;
  email: string;
  roomNumber: string;
  bedType: string;
  school: string;
  address: string;
  guardianName: string;
  localGuardianName: string;
  collegeOrWorkTiming: string;
  dateOfEntry: Date | string;
  status?: string;
  tempUsername?: string;
};

function pdfEscape(value: string) {
  return value.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
}

function formatDate(value: Date | string) {
  const date = value instanceof Date ? value : new Date(value);
  return Number.isNaN(date.getTime()) ? String(value) : date.toDateString();
}

export function createStudentReportPdf(app: ReportApplication) {
  const rows = [
    ['Application ID', String(app._id)],
    ['Status', app.status ?? 'ACCEPTED'],
    ['Full Name', app.fullName],
    ['Phone', app.phone],
    ['Email', app.email],
    ['Room Number', app.roomNumber],
    ['Bed Type', app.bedType],
    ['School / College', app.school],
    ['Address', app.address],
    ['Guardian Name', app.guardianName],
    ['Local Guardian Name', app.localGuardianName],
    ['College / Work Timing', app.collegeOrWorkTiming],
    ['Date of Entry', formatDate(app.dateOfEntry)],
    ['Student Username', app.tempUsername ?? 'Created after acceptance']
  ];

  const text = [
    'BT /F1 18 Tf 50 790 Td (Subidha Girls Hostel - Student Admission Report) Tj ET',
    'BT /F1 10 Tf 50 770 Td (Generated by Subidha Girls Hostel management system.) Tj ET',
    ...rows.map(([label, value], index) => {
      const y = 735 - index * 24;
      return `BT /F1 11 Tf 50 ${y} Td (${pdfEscape(label)}: ${pdfEscape(value)}) Tj ET`;
    })
  ].join('\n');

  const objects = [
    '1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj',
    '2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj',
    '3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj',
    '4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj',
    `5 0 obj << /Length ${Buffer.byteLength(text, 'utf8')} >> stream\n${text}\nendstream endobj`
  ];

  let pdf = '%PDF-1.4\n';
  const offsets = [0];
  for (const obj of objects) {
    offsets.push(Buffer.byteLength(pdf, 'utf8'));
    pdf += `${obj}\n`;
  }

  const xrefOffset = Buffer.byteLength(pdf, 'utf8');
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += '0000000000 65535 f \n';
  for (let i = 1; i < offsets.length; i += 1) {
    pdf += `${String(offsets[i]).padStart(10, '0')} 00000 n \n`;
  }
  pdf += `trailer << /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return Buffer.from(pdf, 'utf8');
}
